version: 2
updates:

  # Maintain dependencies for visit microservices
  - package-ecosystem: "microservices"
    directory: "microservices/game-ms"
    schedule:
      interval: "daily"

  # Maintain dependencies for Ktor microservices
  - package-ecosystem: "microservices"
    directory: "microservices/auth-ms"
    schedule:
      interval: "daily"

# Maintain dependencies for Ktor microservices
  - package-ecosystem: "microservices"
    directory: "microservices/poi-ms"
    schedule:
      interval: "daily"
