### Step 1. Retrieve and save a JWT token.
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jetbrains",
  "password": "foobar"
}

> {% client.global.set("auth_token", response.body.token); %}

### Step 2. Use a JWT token to authorize.
GET http://localhost:8080/hello
Authorization: Bearer {{auth_token}}


### Signup of an user
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "jetbrains1212",
  "password": "foobar"
}

### Signup of an user HTTPS
POST https://172.17.0.2:8443/signup
Content-Type: application/json

{
  "username": "jetbrains1212",
  "password": "foobar"
}

### Delete of an user
POST http://localhost:8080/delete
Content-Type: application/json

{
  "username": "user000",
  "password": "password"
}