name: Android CI

on:
  push:
    branches:
      - android_app
    tags:
      - 'v*'

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartTourist
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Add Maps api key in local.properties
      run: echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} >> local.properties
    - name: Add username for testing
      run: echo USERNAME=${{secrets.TEST_LOGIN_USERNAME}} >> local.properties
    - name: Add password for testing
      run: echo PASSWORD=${{secrets.TEST_LOGIN_PASSWORD}} >> local.properties
    - name: Add keyStore for signing release apk
      run: echo STORE_FILE=smartTouristReleaseKey.jks >> local.properties
    - name: Add password for signing release apk
      run: echo STORE_PASSWORD=${{secrets.ANDROID_APP_SIGNING_PASSWORD}} >> local.properties
    - name: Add keyAlias for signing release apk
      run: echo KEY_ALIAS=${{secrets.ANDROID_APP_ALIAS}} >> local.properties
    - name: Move local.properties in the right folder
      run: mv local.properties SmartTourist

    - name: Create keyStore file in same directory of gradle module app
      run: echo '${{secrets.ANDROID_APP_SIGNING_KEY_BASE64}}' | base64 -d > app/smartTouristReleaseKey.jks
      working-directory: ${{env.working-directory}}

    - name: Run Gradle build
      run: ./gradlew build
      working-directory: ${{env.working-directory}}

    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: SmartTourist/app/build/outputs/apk/

  release_debug_and_release_apk:
    name: Release debug and release APK
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartTourist
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app

    - uses: actions/download-artifact@v3
      with:
        name: apk
        path: SmartTourist/app/build/outputs/apk/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    
    - name: Upload Debug APK
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: SmartTourist/app/build/outputs/apk/debug/app-debug.apk
        asset_name: SmartTouristDebug.apk
        asset_content_type: application/zip

    - name: Upload Release APK
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: SmartTourist/app/build/outputs/apk/release/app-release.apk
        asset_name: SmartTouristRelease.apk
        asset_content_type: application/zip

  pull-request:
    name: Pull request
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
