name: Android CI

on: 
  push:
    branches:
      - android_app
    tags:
      - 'v*'

jobs:
  build: 
    name: Build project
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartTourist
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create local.properties
      run: echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} > local.properties
      working-directory: ${{env.working-directory}}
    - name: Run Gradle build
      run: ./gradlew build
      working-directory: ${{env.working-directory}}
  
  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartTourist
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    #common part in defining java version
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create local.properties
      run: echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} > local.properties
      working-directory: ${{env.working-directory}}
    - name: Run Gradle tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

  release_debug_apk:
    name: Generate and release debug APK
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartTourist
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create local.properties
      run: echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} > local.properties
      working-directory: ${{env.working-directory}}
    - name: Build debug APK
      run: ./gradlew assembleDebug
      working-directory: ${{env.working-directory}}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }} 
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: SmartTourist/app/build/outputs/apk/debug/app-debug.apk
        asset_name: SmartTouristDebug.apk
        asset_content_type: application/zip
     
  pull-request:
    name: Pull request
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
