name: Build and deploy auth microservice

on:
  push:
    branches: [ server ]

jobs:
      
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./ktor-auth-ms
    steps:
    - uses: actions/checkout@v3
    #common part in defining java version
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Run Gradle tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}
   
  deploy:
    name: Deploy to Heroku
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "smart-tourist-auth" #Must be unique in Heroku
          heroku_email: "lucarossi147@gmail.com"
          appdir: "ktor-auth-ms" # <- This will point to the api folder in your project
