name: Deploy to GCP

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          #IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
          IMAGE_NAME: gcr.io/smarttourist22/smart-tourist
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            #project_id: ${{ secrets.GCP_PROJECT_ID }}
            #service_account_email: ${{ secrets.GCP_EMAIL }}
            #service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            project_id: smarttourist22
            service_account_email: dados1998@smarttourist22.iam.gserviceaccount.com
            service_account_key: {
  "type": "service_account",
  "project_id": "smarttourist22",
  "private_key_id": "e94c5679adfc584354232adba3caa7dd5e841148",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRfsoUT/0vVo5W\nQZ5go86XZa5fMDrbc+wmknUTa81CslT6UifTuq+jgeqOsgG7EGv0OMBTL1EoaLBu\nTobJ9z0dshjEKZzK/OZYhXN6P7J/YR/dpafo3ehetdCX+4YRTbO/+3SyAbFpoU8r\nuAQQ3M0tkAcntbZH7IHyhNysNOLZEdyf+mJ2kKr9Q+qRsARsQZa5Zvs6XTZ02dVI\nnOWsynZT6jldsX+eoT+xhv3CUFAWJ3z/6CmC+LaYX5xvbu6XQ59al2yZjK4Dd5AG\nxGaYHtk0KDbVRdTE0WnVx5WZ8SNadTC1iHFbdSClqH6HVNN1X/WsiAglL7Xx/yBw\nGX4MVLEJAgMBAAECggEABS/EI+e7EpQvFEeYDgFg5LhA+E83lemivjhD2Kqj4VAK\no/bISS2zQ6ymsCoL0j+SXZ0lTAHYjox216PQfcQkx1l5NQr3tivASWEOfgnlwtEz\nSds1KmG4viGUm0ph292NfhdIcG0LhkS0Fg6kBHbekJR9EM8TPaqickMGu9PRz2Oc\nG4XqHwK3ew794/dGg3sFpaI/9fJR02AIxaIdRMo3GQcGPdtDa7DWyNiWCNDppJ0+\n8BYl5cMFMZ4e2DShej2LCvSmU47UwWRaBI1wT+7s0O8x0KITfAtzH1Ndf1bWvCrE\nKWM6EcBVrwOcnzjbRCt7I7jcmvO8wU4hrM33PS4JoQKBgQDBgjR+r4Bm/bHSaJXz\nKke7DAjJS46j39ItdWLfH8yIllr8vICVRzCZRrzvxezBy4HUVCRjaCOfN85aQXZ3\nHkJVFMREoW8XsmDRfQYT95yKgUmmDcCWpR8kWDgVTaECIaz94Ezx+8ysMVjaRz+W\nAnoVpxlqxpkUdL7/eZ9VW1mgmQKBgQDAezZv72ffpm6736q2MsSr93QZo9NIL2mL\n+V884lq5vzCWW/AK6x8umfn6/CXsTlSC25X4514RXNy05hArjLoIqdkK2ooy4Nex\nQycs+Uug3qT0kYLDqG29a4lUVc80NJcudduKOWYO5IpqOE4qrkoFsYzuiCmwMgK9\ngEFWnZwp8QKBgH8C/4HHn/f5vKXmj8WzkrFrDLlTJqTZXBMKYYMiVBWy2rXY5G0W\n9QcmLw0SVHw/H1BGijvVNsxizMbhAOjeq5s8rjZ933UmV/YoobypYc5nXffoPuii\nKPaqEOWqtmu3vtxERTzvkT/UhAWBjnLf3VIpA73Z7NBIcLUvFy3nb8TBAoGAee0S\nvLEgUXGx71xtXOCn6G7lomA+NBmkeEBM7dpMsiDD/FrcoW3y4Kg0y6Hxu9CahBHo\n3DRjSAhU3lpln9CS/23nyJJKvJPkzarGJBz+pTajszCBbsNAUJ7P7RY2HNG7eni5\nysM1PPXUIBjumuawiQ7BQVALaEslpTibKuzHwWECgYBLfP9HZ6lfhqftipDZi/xJ\ncxSNygh6qjWUvcNo77byNxVhrmDI2X/TYy2ZLwUGq4xZcRufLBBpL9xbHpSQT+a0\ndsf1gcZzDgk71GGALmUHQvQHNRQOAKCtxw2xS327VNM9TzGhwV0XQn/adVLKM/37\nk8DzTdn/kJpH8j+ivR3D8w==\n-----END PRIVATE KEY-----\n",
  "client_email": "dados1998@smarttourist22.iam.gserviceaccount.com",
  "client_id": "117042950178991804062",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dados1998%40smarttourist22.iam.gserviceaccount.com"
}


        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
          run: export IMAGE_NAME=auth-container
          
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        #- name: Test Docker image
        #  run: docker run $IMAGE_NAME sh -c "go test -v"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy smarttourist22 --image $IMAGE_NAME --region us-central1 --platform managed
