name: Check if build work properly every day
on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartTourist
    steps:
    - uses: actions/checkout@v3
      with:
        ref: android_app
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Add Maps api key in local.properties
      run: echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} >> local.properties
    - name: Add username for testing
      run: echo USERNAME=${{secrets.TEST_LOGIN_USERNAME}} >> local.properties
    - name: Add password for testing
      run: echo PASSWORD=${{secrets.TEST_LOGIN_PASSWORD}} >> local.properties
    - name: Add keyStore for signing release apk
      run: echo STORE_FILE=smartTouristReleaseKey.jks >> local.properties
    - name: Add password for signing release apk
      run: echo STORE_PASSWORD=${{secrets.ANDROID_APP_SIGNING_PASSWORD}} >> local.properties
    - name: Add keyAlias for signing release apk
      run: echo KEY_ALIAS=${{secrets.ANDROID_APP_ALIAS}} >> local.properties
    - name: Move local.properties in the right folder
      run: mv local.properties SmartTourist

    - name: Create keyStore file in same directory of gradle module app
      run: echo '${{secrets.ANDROID_APP_SIGNING_KEY_BASE64}}' | base64 -d > app/smartTouristReleaseKey.jks
      working-directory: ${{env.working-directory}}

    - name: Run Gradle build
      run: ./gradlew build
      working-directory: ${{env.working-directory}}
