name: Deploy POI to Cloud Run

on:
  push:
    branches: [ server ]
    paths: 
      - 'microservices/poi-ms/**/*.kt'
      - 'microservices/poi-ms/build.gradle.kts'
      - '.github/workflows/poi-deploy.yml'

jobs:

    deploy:
        name: Deploy poi service
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_POI_NAME }}
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build ./microservices/poi-ms/ -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_POI_NAME }} --image $IMAGE_NAME --set-env-vars DB_PWD=${{secrets.DB_PWD}}t --port=3000 --region us-central1 --platform managed
