name: Kotlin CI with Gradle

on:
  push:
    branches: [ server ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./ktor-auth-ms
    steps:
    - uses: actions/checkout@v3
    #common part in defining java version
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Run Gradle tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}
